/*===========================================================================*=
	Master_Telescope - Vitesse Moteur - Tanguy Dietrich
  =============================================================================
   Descriptif: Definition des vitesse de suivi pour les moteur

=*===========================================================================*/

#define VITESSE_RA_SIDERAL 0
#define VITESSE_RA_LUNE 1
#define VITESSE_RA_SOLEIL 2
#define VITESSE_RA_SATURNE 3
#define VITESSE_RA_JUPITER 4
#define VITESSE_RA_ISS 5
#define VITESSE_X05 6
#define VITESSE_X2 7
#define VITESSE_X8 8
#define VITESSE_X16 9
#define VITESSE_MAX 10

#define DIR_POS 0
#define DIR_NEG 1

#define VITESSE_RA_SIDERAL_LOAD 39565 //39565 pour vitesse siderale = (1/19.25)/2 = 25.97ms
#define VITESSE_RA_SIDERAL_HIGH VITESSE_RA_SIDERAL_LOAD/256
#define VITESSE_RA_SIDERAL_LOW VITESSE_RA_SIDERAL_LOAD%256

#define VITESSE_RA_LUNE_LOAD 40669
#define VITESSE_RA_LUNE_HIGH VITESSE_RA_LUNE_LOAD/256
#define VITESSE_RA_LUNE_LOW VITESSE_RA_LUNE_LOAD%256

#define VITESSE_RA_SOLEIL_LOAD 39640
#define VITESSE_RA_SOLEIL_HIGH VITESSE_RA_SOLEIL_LOAD/256
#define VITESSE_RA_SOLEIL_LOW VITESSE_RA_SOLEIL_LOAD%256

#define VITESSE_RA_SATURNE_LOAD 39569
#define VITESSE_RA_SATURNE_HIGH VITESSE_RA_SATURNE_LOAD/256
#define VITESSE_RA_SATURNE_LOW VITESSE_RA_SATURNE_LOAD%256

#define VITESSE_RA_JUPITER_LOAD 39575
#define VITESSE_RA_JUPITER_HIGH VITESSE_RA_JUPITER_LOAD/256
#define VITESSE_RA_JUPITER_LOW VITESSE_RA_JUPITER_LOAD%256

#define VITESSE_RA_ISS_LOAD 65463 //ne fonctionne pas
#define VITESSE_RA_ISS_HIGH VITESSE_RA_ISS_LOAD/256
#define VITESSE_RA_ISS_LOW VITESSE_RA_ISS_LOAD%256

#define VITESSE_RA_X05_LOAD 13594 //
#define VITESSE_RA_X05_HIGH VITESSE_RA_X05_LOAD/256
#define VITESSE_RA_X05_LOW VITESSE_RA_X05_LOAD%256

#define VITESSE_RA_X1_5_LOAD 48222 //
#define VITESSE_RA_X1_5_HIGH VITESSE_RA_X1_5_LOAD/256
#define VITESSE_RA_X1_5_LOW VITESSE_RA_X1_5_LOAD%256

#define VITESSE_RA_X2_LOAD 52550 //
#define VITESSE_RA_X2_HIGH VITESSE_RA_X2_LOAD/256
#define VITESSE_RA_X2_LOW VITESSE_RA_X2_LOAD%256

#define VITESSE_RA_X8_LOAD 62289 //63912  - x16
#define VITESSE_RA_X8_HIGH VITESSE_RA_X8_LOAD/256
#define VITESSE_RA_X8_LOW VITESSE_RA_X8_LOAD%256

#define VITESSE_RA_X16_LOAD 63912 //63912  - x16
#define VITESSE_RA_X16_HIGH VITESSE_RA_X16_LOAD/256
#define VITESSE_RA_X16_LOW VITESSE_RA_X16_LOAD%256

#define VITESSE_RA_MAX_LOAD 64995//x48 
#define VITESSE_RA_MAX_HIGH VITESSE_RA_MAX_LOAD/256
#define VITESSE_RA_MAX_LOW VITESSE_RA_MAX_LOAD%256


#define VITESSE_DEC_X05 96 //118.0
#define VITESSE_DEC_X2 24 //29.5
#define VITESSE_DEC_X8 6 //7,38
#define VITESSE_DEC_X16 3 //3,69
#define VITESSE_DEC_MAX 1 //1,0